export enum Genre {
  Roman = "Роман",
  HistoricalProse = "Историческая проза",
  Epic = "Эпопея",
  PsychologicalNovel = "Психологический роман",
  Drama = "Драма",
  PhilosophicalLiterature = "Философская литература",
  Fantasy = "Фэнтези",
  Satire = "Сатира",
  Philosophy = "Философия",
  JuvenileLiterature = "Юношеская литература",
  Adventure = "Приключения",
  HistoricalNovel = "Исторический роман",
  Romance = "Романтика",
  MilitaryProse = "Военная проза",
  PsychologicalProse = "Психологическая проза",
  Dystopia = "Антиутопия",
  ScienceFiction = "Научная фантастика",
  ShortStory = "Повесть",
  Allegory = "Аллегория",
  CourtDrama = "Судебная драма",
  SocialProse = "Социальная проза",
  PoeticProse = "Поэтическая проза",
  Autobiography = "Автобиография"
}
